# Generated by Django 6.0.2 on 2026-02-18 14:57

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studdog',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
