name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build project
        working-directory: frontend
        run: |
          npm ci
          npx vite build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Build Admin project
        working-directory: admin-panel
        run: |
          npm ci
          npx vite build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Merge Admin into Frontend
        run: mkdir -p frontend/dist/admin-panel && cp -r admin-panel/dist/* frontend/dist/admin-panel/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

      - uses: actions/deploy-pages@v4